### ISSUE TITLE
Switch modules src to ES6 modules

### ISSUE THREAD

**Issue by skddc** [remotestorage/modules#35]
... transpiling to ES5-compatible JavaScript during build.

It's much cleaner and we can switch to the native implementation soon.

Here's what most people use for this: https://github.com/square/es6-module-transpiler

I think we should also consider it for rs.js core.

**Comment by skddc** [comment]
I think the best way is introducing Gulp for task automation and Babel (ex 6to5) for compilation of ES6 to ES5 (all of it, not just modules).

Reasons:

* Babel is the most popular and basically de-facto transpiler now it seems. Has libs for all environments and task runners in existence.
* Gulp seems to me like the task runner that is easiest to grasp for people who aren't familiar with it. It's popular enough (1300+ plugins) and very concise. @silverbucket is using it in some projects already iirc.

If nobody thinks that this is a terrible idea (comments welcome!), I'll probably play with it during one of the next weekends and start a PR.

Question is obviously if we want to (or even have to) provide a module-builder tool/webpage, where you can click which ones you want and just download the final build for them. In any case it must be easy to do it via the command line by issuing a command with the module names as args or something.

**Comment by silverbucket** [comment]
I think this sounds like a good idea. A web page / tool would be nice down the road. Something simple for starters would be good while we figure out how it will all end up looking like.

**Comment by skddc** [comment]
I played around with this tonight and got stuck real hard with Gulp. In the end I just used browserify and babelify via console and got my bookmarks module to build with an included ES6 module for md5sum.

It's in the `es6` branch, but it's going to take some more work before I can start a PR.

From the utils in `src/utils` I could only see `CredentialsStore` being used in modules in this repo (only did some quick greps, though). @michielbdejong Does that mean you developed the other utils for modules that aren't published yet?

@silverbucket Is there an app, with which I can test the `-credentials` modules when I move them to ES6?

**Comment by michielbdejong** [comment]
@skddc Correct, I [developed `PrefixTree` for email storage, in the meute repo](https://github.com/michielbdejong/meute/blob/93f7a75415f4b8844f4838bad5acb38124760300/upstream/remotestorage-modules/email.js#L38) but that module [disappeared again](https://github.com/michielbdejong/meute/commit/1bb75d6733dff84bf1367ef68ba3af5bce7baa36) without ever making it into the official modules repo.

I think the reason was that both meute and dogfeed were storing messages, and it was easier for  me to adapt meute to dogfeed than to adapt dogfeed to meute, and that's why the dogfeed one became the official and universally used one.

It [uses a date-based tree](https://github.com/remotestorage/modules/blob/master/src/messages.js#L38-L40) instead of a PrefixTree. And since we haven't done a lot of module development since PrefixTree, none of the current modules use it.

**Comment by skddc** [comment]
Ok, then I'll just convert them after I make sure that the concept/code works for `CredentialsStore`.

**Comment by skddc** [comment]
Ok, now you can run "make build-all" to build all module files in `src` to `dist`.

**Comment by skddc** [comment]
Now all done via Grunt, including a watch task for development: https://github.com/remotestorage/modules/pull/73

**Comment by silverbucket** [comment]
Hi @skddc and @michielbdejong I don't think there is currently an app which uses a recent version of remoteStorage that uses the credentials module. Most of the apps I worked on are out-dated and I haven't put the effort into updating them yet. There seemed to have been a lot of breaking changes over the past year and I didn't have the time to work through them. Also, with dogfeed, I'd like to update it to use the new AS2.0 format for Sockethub2 - at which point I will also update it to use the latest remoteStorage.

**Comment by michielbdejong** [comment]
@silverbucket Great! When I was working on meute last year, I tried to stay as close as possible to your existing modules, instead of reinventing the wheel.

There is not one "credentials" module though. There are various "something-credentials" modules, which all use the CredentialsStore class. The modules in this repo were last updated in November, by me, to match what [meute 0.7.1](https://meute.5apps.com/) uses: https://github.com/remotestorage/modules/tree/master/src. Apart from meute, [the encryption example in the starter-kit](https://github.com/remotestorage/starter-kit/tree/master/apps/encryption_experimental_) uses the CredentialsStore class (but it's not using any of the modules).

About the sockethub-credentials module, let's move that to a separate issue, I created #74

**Comment by skddc** [comment]
@silverbucket Thanks for the update!

> There seemed to have been a lot of breaking changes over the past year

Actually there should only be one: the changing of the directory listing format. If you want to pair on it, I can walk you through updating the apps. Shouldn't take more than 10 minutes each. ;)

**Comment by skddc** [comment]
@silverbucket Any news? I'm hesitant to do a PR for this without having tested half of the modules in an actual app.

**Comment by silverbucket** [comment]
Hey @skddc I guess I misunderstood this. There is no app which uses @michielbdejong's encryption, addition, if that's what you wanted to test? Other than that, the credential modules are just very basic JSON data structs, not much going on there that would need specific testing. Or am I misunderstanding? :)

**Comment by skddc** [comment]
Yes, I want to test the modules using the credentials util in real apps.

**Comment by skddc** [comment]
All done and merged. See README for info about how to watch/build during development and after.

Thanks again @pixelkritzel for helping out with the Grunt setup!
